# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pesoideal.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'pesoideal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpesoideal.proto\"0\n\x10PesoIdealRequest\x12\x0e\n\x06\x61ltura\x18\x01 \x01(\x01\x12\x0c\n\x04sexo\x18\x02 \x01(\t\"&\n\x11PesoIdealResponse\x12\x11\n\tpesoIdeal\x18\x01 \x01(\x01\x32N\n\x10PesoIdealService\x12:\n\x11\x43\x61lcularPesoIdeal\x12\x11.PesoIdealRequest\x1a\x12.PesoIdealResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pesoideal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PESOIDEALREQUEST']._serialized_start=19
  _globals['_PESOIDEALREQUEST']._serialized_end=67
  _globals['_PESOIDEALRESPONSE']._serialized_start=69
  _globals['_PESOIDEALRESPONSE']._serialized_end=107
  _globals['_PESOIDEALSERVICE']._serialized_start=109
  _globals['_PESOIDEALSERVICE']._serialized_end=187
# @@protoc_insertion_point(module_scope)
