# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pesoideal_pb2 as pesoideal__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pesoideal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PesoIdealServiceStub(object):
    """Definição do serviço
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalcularPesoIdeal = channel.unary_unary(
                '/PesoIdealService/CalcularPesoIdeal',
                request_serializer=pesoideal__pb2.PesoIdealRequest.SerializeToString,
                response_deserializer=pesoideal__pb2.PesoIdealResponse.FromString,
                _registered_method=True)


class PesoIdealServiceServicer(object):
    """Definição do serviço
    """

    def CalcularPesoIdeal(self, request, context):
        """Método RPC para calcular o peso ideal
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PesoIdealServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalcularPesoIdeal': grpc.unary_unary_rpc_method_handler(
                    servicer.CalcularPesoIdeal,
                    request_deserializer=pesoideal__pb2.PesoIdealRequest.FromString,
                    response_serializer=pesoideal__pb2.PesoIdealResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PesoIdealService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PesoIdealService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PesoIdealService(object):
    """Definição do serviço
    """

    @staticmethod
    def CalcularPesoIdeal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PesoIdealService/CalcularPesoIdeal',
            pesoideal__pb2.PesoIdealRequest.SerializeToString,
            pesoideal__pb2.PesoIdealResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
